### ISSUE TITLE
请问下

### ISSUE THREAD

**Issue by lqsunshine** [yongzhuo/Macropodus#1]
想请问一下，对于命名实体识别，您是用albert训练的模型吗，用的什么数据集。如果我想用自己的数据训练数据可行吗，刚入门nlp，请教下

**Comment by yongzhuo** [comment]
你可以用自己的训练集训练，训练脚本在macropodus/network/train目录，数据格式参考master/macropodus/data/corpus/ner_people_1998目录语料格式。
数据集使用的是1998人民日报语料、BOSON语料以及自己的语料合在一起。
