### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by qa8306202** [yongzhuo/Macropodus#2]
请问训练自己的数据集，是按照data/train/corpus/下面的train.json格式来制作自己的数据集来训练吗？
想问一下，您当时只使用了train.json中的数据进行训练，还是使用了整个ChineseNER外加自己的数据？

**Comment by yongzhuo** [comment]
是train.json那样的格式。训练时候用了整个ChineseNER外加自己的数据

**Comment by qa8306202** [comment]
您好，我想微调一下模型，使用自己的数据集来做question-question相似度匹配，请问如何操作？应该不是使用NER格式的吧

**Comment by yongzhuo** [comment]
目前文本分类没有集成
