### ISSUE TITLE
想确定下是否支持文本分类/多标签分类

### ISSUE THREAD

**Issue by RyanOvO** [yongzhuo/Macropodus#25]
看readme上是没有文本分类任务的支持。但还是想确定下，是否支持文本分类/多标签分类/层次分类呢？

**Comment by yongzhuo** [comment]
这个是NLP基础工具包，没有你想要的呢，多标签分类/层次分类推荐项目 [https://github.com/Tencent/NeuralNLP-NeuralClassifier](https://github.com/Tencent/NeuralNLP-NeuralClassifier)

**Comment by yongzhuo** [comment]
如果你想要已经做好的，推荐zeroshot-classification，如[facebook/bart-large-mnli](https://hf-mirror.com/facebook/bart-large-mnli), [Jiva/xlm-roberta-large-it-mnli](https://hf-mirror.com/Jiva/xlm-roberta-large-it-mnli)

**Comment by RyanOvO** [comment]
好的，感谢
