### ISSUE TITLE
安装时报错，无法找到nlg-yongzhuo正确版本

### ISSUE THREAD

**Issue by QUENTINNE** [yongzhuo/Macropodus#4]
你好，在终端输入pip install -i https://pypi.tuna.tsinghua.edu.cn/simple macropodus

安装时报以下错误：

**Collecting nlg-yongzhuo==0.0.4 (from macropodus)
  ERROR: Could not find a version that satisfies the requirement nlg-yongzhuo==0.0.4 (from macropodus) (from versions: 0.0.2)
ERROR: No matching distribution found for nlg-yongzhuo==0.0.4 (from macropodus)**

**Comment by yongzhuo** [comment]
pip应该可以，不要用清华镜像源，今天更新的，清华镜像源可能还没有同步
