### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by GuiminDragon** [yongzhuo/Macropodus#9]
看起来这个库功能很不错，但我的oycharm已装了numpy ,pandas, 在pip install macropodus之后它会重新下载numpy,pandas安装包，接着报错failed building wheel XXXXXX. 能提供一下解决的思路吗？

**Comment by yongzhuo** [comment]
可以考虑以下方法，但是不保证兼容很新、或者很久的包：

1. 首先克隆该项目代码
git clone https://github.com/yongzhuo/Macropodus.git
2. 然后修改项目依赖文件requirements.txt文件
   2.1 可以将源代码中requirements.txt文件中的pandas,numpy改为pandas>=0.23.4,numpy>=1.16.2
   2.2 或者是将pandas,numpy从文件中删除
3. 在本地重新打包成.whl文件
   python setup.py bdist_wheel --universal
4. 然后直接pip安装就可以了
